language: csharp
sudo: false

env:
  global:
    - CONFIGURATION="Release"
mono:
  - 3.12.0
  - 3.10.0
solution: Persimmon.Dried.sln

install:
  - nuget install Persimmon.Console -Pre -OutputDirectory packages -ExcludeVersion

script:
  - xbuild ./Persimmon.Dried.sln /p:Configuration=${CONFIGURATION}
  - mono --runtime=v4.0 ./packages/Persimmon.Console/tools/Persimmon.Console.exe --parallel ./tests/Persimmon.Dried.Tests/bin/${CONFIGURATION}/Persimmon.Dried.Tests.dll ./tests/Persimmon.Dried.CSharp.Tests/bin/${CONFIGURATION}/Persimmon.Dried.CSharp.Tests.dll

