language: csharp
sudo: false

mono:
  - 4.2.2
  - 3.12.0
  - 3.10.0
solution: Persimmon.Dried.sln

before_script:
 - chmod +x ./build.sh
script:
  - ./build.sh

cache:
  directories:
    - paket-files
    - packages
