version: 1.0.{build}

branches:
  except:
    - gh-pages

skip_tags: true

skip_commits:
  message: \[(ci skip|skip ci)\].*

clone_depth: 50

configuration:
  - Release

test_script:
  - .\.nuget\NuGet.exe Install Persimmon.Console -Pre -OutputDirectory packages -ExcludeVersion
  - ps: Copy-Item -Force .\packages\Persimmon.Console\tools\* .\tests\Persimmon.Dried.Tests\bin\$env:configuration\
  - ps: Start-Process -FilePath ".\tests\Persimmon.Dried.Tests\bin\$env:configuration\Persimmon.Console.exe" -ArgumentList ".\tests\Persimmon.Dried.Tests\bin\$env:configuration\Persimmon.Dried.Tests.dll"
