version: 1.2.1.{build}

branches:
  except:
    - gh-pages

skip_tags: true

skip_commits:
  message: \[(ci skip|skip ci)\].*

clone_depth: 50

configuration:
  - Release

test_script:
  - .\.nuget\NuGet.exe Install Persimmon.Console -Pre -OutputDirectory packages -ExcludeVersion
  - ps: .\packages\Persimmon.Console\tools\Persimmon.Console.exe --parallel .\tests\Persimmon.Dried.Tests\bin\$env:configuration\Persimmon.Dried.Tests.dll .\tests\Persimmon.Dried.CSharp.Tests\bin\$env:configuration\Persimmon.Dried.CSharp.Tests.dll
