branches:
  except:
    - gh-pages

configuration:
  - Release

test_script:
  - .\.nuget\NuGet.exe Install Persimmon.Console -Pre -OutputDirectory packages -ExcludeVersion
  - ps: Copy-Item -Force .\packages\Persimmon.Console\tools\* .\tests\Persimmon.Dried.Tests\bin\$env:configuration\
  - ps: Start-Process -FilePath ".\tests\Persimmon.Dried.Tests\bin\$env:configuration\Persimmon.Console.exe" -ArgumentList ".\tests\Persimmon.Dried.Tests\bin\$env:configuration\Persimmon.Dried.Tests.dll"
